### ISSUE TITLE
[REQUEST] Activate a flag to prevent a character with a paladin dip from generating an aura

### ISSUE THREAD

**Issue by XPHogToo** [LaytonGB/PaladinAura#41]
**Is your feature request related to a problem? Please describe.**
I have 2 paladins in the party, one which generates the aura and a second with a single level dip and should not generate an aura but both are doing so right now.

**Describe the solution you'd like**
An ability to apply a flag or add an attribute to the paladin that does not generate an aura to prevent him from doing so with the script.

**Describe alternatives you've considered**
None.

**Comment by LaytonGB** [comment]
Hi will get on this ASAP but my Roll20 membership has actually expired so I can't test the code :S

I'll let you know when its ready and hopefully you can give it a try.

**Comment by LaytonGB** [comment]
Sorry, this project is actually depreciated now in favour of the newer, faster version from the Roll20 API one-click-addon list. 

You can also find it on GitLab [here](https://gitlab.com/LaytonGB/Paladin-Aura-API).

**Comment by XPHogToo** [comment]
Looks like it is working great! Thank you!

Best regards,
Ron
